version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: product_management_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: product_management
    ports:
      - "9999:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: always
volumes:
  postgres_data:
