spring:
  application:
    name: QIMA-assessment
  #  autoconfigure:
  #    exclude:
  #      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/nome_do_banco
    username: seu_usuario
    password: sua_senha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:secret-key}
