spring:
  application:
    name: studieDemo
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: ${PORT:8080}
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:secret-key}
