spring:
  application:
    name: QIMA-assessment
  #  autoconfigure:
  #    exclude:
  #      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:9999/product_management
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8888}
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:secret-key}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  enable-data-rest: false
